### ISSUE TITLE
NullPointerException when no token is entered

### ISSUE THREAD

**Issue by seeseemelk** [HuffleAnimations/Mongoose#1]
The following error occurs when there is no token property:
```
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:222)
        at discord4j.core.DiscordClientBuilder.<init>(DiscordClientBuilder.java:129)
        at be.huffle.mongoose.Mongoose.run(Mongoose.java:28)
        at be.huffle.mongoose.App.main(App.java:9)
```

**Comment by HuffleAnimations** [comment]
Fixed it
